### ISSUE TITLE
kubernetes yaml for this docker image.

### ISSUE THREAD

**Issue by MaheshIBM** [angoca/db2-docker#21]
It would be good if the kubernetes yaml file for this image is documented somewhere. I am trying to use this with kubernetes and mount a persistent volume for the /home directory.

**Comment by MaheshIBM** [comment]
Below is the yaml
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: db2-angoca
  labels:
    tier: db2-database
spec:
  containers:
  - name: db2-angoca-container
    image: angoca/db2inst1:expc
    command: ["/bin/sh"]
    args: ["-c", "/home/db2inst1/sqllib/adm/db2start;while true; do echo hello; sleep 10;done"]
    ports:
      - containerPort: 50000
    securityContext:
      privileged: true

```
